//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerValidationToolkit.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlServerValidationToolkit.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///------------------------------------------------------
        ///------------------------------------------------------
        ///----------------Procedures
        ///------------------------------------------------------
        ///------------------------------------------------------
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///---------------------------------------------------------------[Validation_USP_Update_corrected_Values]------------------------------------------------------------------
        ///
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProceduresAndFunctions {
            get {
                return ResourceManager.GetString("ProceduresAndFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF (EXISTS(SELECT * FROM [__MigrationHistory]))
        ///BEGIN
        ///	DROP TABLE [dbo].[__MigrationHistory]
        ///END
        ///
        ///DROP TABLE [dbo].[Validation_TempId]
        ///
        ///DROP TABLE [dbo].[Validation_WrongValue]
        ///
        ///
        ///DROP TABLE [dbo].[Validation_ValidationRule_ErrorType]
        ///
        ///DROP TABLE [dbo].[Validation_Errortype]
        ///
        ///DROP TABLE [dbo].[Validation_ValidationRule]
        ///
        ///DROP TABLE [dbo].[Validation_Column]
        ///
        ///
        ///DROP TABLE [dbo].[Validation_Log]
        ///
        ///DROP TABLE [dbo].[Validation_Source]
        ///
        ///--drop stored procedures
        ///DROP PROCEDURE [dbo].[Valid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UninstallToolkit {
            get {
                return ResourceManager.GetString("UninstallToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW Validation_ColumnsWithWrongValues
        ///AS
        ///SELECT 
        ///	DISTINCT -- distinct because the entry could contain multiple wrong values
        ///	wv.[Id],
        ///	c.Name as columnName,
        ///	s.Name as sourceName
        ///  FROM [dbo].[Validation_WrongValue] wv
        ///  JOIN dbo.Validation_ValidationRule vr ON wv.ValidationRule_fk = vr.ValidationRule_id
        ///  JOIN dbo.Validation_Column c ON vr.Column_fk = c.Column_id
        ///  JOIN dbo.Validation_Source s ON c.Source_fk = s.Source_id
        ///.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
